from gi.repository import GLib

# constants

NOTIFICATION_WIDTH = 400
NOTIFICATION_IMAGE_SIZE = 64
NOTIFICATION_TIMEOUT = 5  # 5 seconds
HIGH_POLL_INTERVAL = 1000 * 3600  # 1 hour

APPLICATION_NAME = "hydepanel"
SYSTEM_CACHE_DIR = GLib.get_user_cache_dir()
APP_CACHE_DIRECTORY = f"{SYSTEM_CACHE_DIR}/{APPLICATION_NAME}"


NOTIFICATION_CACHE_FILE = f"{APP_CACHE_DIRECTORY}/notifications.json"
WEATHER_CACHE_FILE = f"{APP_CACHE_DIRECTORY}/weather.json"
