common_text_icons = {
    "playing": "",
    "paused": "",
    "power": "",
    "cpu": "",
    "memory": "",
    "storage": "󰋊",
    "updates": "󱧘",
    "thermometer": "",
}

distro_text_icons = {
    "deepin": "",
    "fedora": "",
    "arch": "",
    "nixos": "",
    "debian": "",
    "opensuse-tumbleweed": "",
    "ubuntu": "",
    "endeavouros": "",
    "manjaro": "",
    "popos": "",
    "garuda": "",
    "zorin": "",
    "mxlinux": "",
    "arcolinux": "",
    "gentoo": "",
    "artix": "",
    "centos": "",
    "hyperbola": "",
    "kubuntu": "",
    "mandriva": "",
    "xerolinux": "",
    "parabola": "",
    "void": "",
    "linuxmint": "",
    "archlabs": "",
    "devuan": "",
    "freebsd": "",
    "openbsd": "",
    "slackware": "",
}

# sourced from wttr.in
weather_icons = {
    "113": {
        "description": "Sunny",
        "icon": "󰖙",
        "image": "clear-day",
        "icon-night": "󰖙",
        "image-night": "clear-night",
    },
    "116": {
        "description": "PartlyCloudy",
        "icon": "󰖕",
        "image": "partly-cloudy-day",
        "icon-night": "󰖕",
        "image-night": "partly-cloudy-night",
    },
    "119": {
        "description": "Cloudy",
        "icon": "󰖐",
        "image": "cloudy",
        "icon-night": "󰖐",
        "image-night": "cloudy",
    },
    "122": {
        "description": "VeryCloudy",
        "icon": "󰖕",
        "image": "cloudy",
        "icon-night": "󰖕",
        "image-night": "cloudy",
    },
    "143": {
        "description": "Fog",
        "icon": "󰖑",
        "image": "fog",
        "icon-night": "󰖑",
        "image-night": "fog-night",
    },
    "176": {
        "description": "LightShowers",
        "icon": "󰼳",
        "image": "rain",
        "icon-night": "󰼳",
        "image-night": "rain",
    },
    "179": {
        "description": "LightSleetShowers",
        "icon": "󰼵",
        "image": "sleet",
        "icon-night": "󰼵",
        "image-night": "sleet",
    },
    "182": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "185": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "200": {
        "description": "ThunderyShowers",
        "icon": "󰙾",
        "image": "thunderstorms",
        "icon-night": "󰙾",
        "image-night": "thunderstorms-night",
    },
    "227": {
        "description": "LightSnow",
        "icon": "󰼴",
        "image": "snow",
        "icon-night": "󰼴",
        "image-night": "snow",
    },
    "230": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "snow",
        "icon-night": "󰼶",
        "image-night": "snow",
    },
    "248": {
        "description": "Fog",
        "icon": "󰖑",
        "image": "fog",
        "icon-night": "󰖑",
        "image-night": "fog",
    },
    "260": {
        "description": "Fog",
        "icon": "󰖑",
        "image": "fog",
        "icon-night": "󰖑",
        "image-night": "fog-night",
    },
    "263": {
        "description": "LightShowers",
        "icon": "󰼳",
        "image": "rain",
        "icon-night": "󰼳",
        "image-night": "rain",
    },
    "266": {
        "description": "LightRain",
        "icon": "󰼳",
        "image": "rain",
        "icon-night": "󰼳",
        "image-night": "rain",
    },
    "281": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "284": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "293": {
        "description": "LightRain",
        "icon": "󰼳",
        "image": "rain",
        "icon-night": "󰼳",
        "image-night": "rain",
    },
    "296": {
        "description": "LightRain",
        "icon": "󰼳",
        "image": "rain",
        "icon-night": "󰼳",
        "image-night": "rain",
    },
    "299": {
        "description": "HeavyShowers",
        "icon": "󰖖",
        "image": "rain",
        "icon-night": "󰖖",
        "image-night": "rain",
    },
    "302": {
        "description": "HeavyRain",
        "icon": "󰖖",
        "image": "rain",
        "icon-night": "󰖖",
        "image-night": "rain",
    },
    "305": {
        "description": "HeavyShowers",
        "icon": "󰖖",
        "image": "rain",
        "icon-night": "󰖖",
        "image-night": "rain",
    },
    "308": {
        "description": "HeavyRain",
        "icon": "󰖖",
        "image": "rain",
        "icon-night": "󰖖",
        "image-night": "rain",
    },
    "311": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "314": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "317": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "320": {
        "description": "LightSnow",
        "icon": "󰼴",
        "image": "snow",
        "icon-night": "󰼴",
        "image-night": "snow",
    },
    "323": {
        "description": "LightSnowShowers",
        "icon": "󰼵",
        "image": "snow",
        "icon-night": "󰼵",
        "image-night": "snow",
    },
    "326": {
        "description": "LightSnowShowers",
        "icon": "󰼵",
        "image": "snow",
        "icon-night": "󰼵",
        "image-night": "snow",
    },
    "329": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "snow",
        "icon-night": "󰼶",
        "image-night": "snow",
    },
    "332": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "snow",
        "icon-night": "󰼶",
        "image-night": "snow",
    },
    "335": {
        "description": "HeavySnowShowers",
        "icon": "󰼵",
        "image": "snow",
        "icon-night": "󰼵",
        "image-night": "snow",
    },
    "338": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "snow",
        "icon-night": "󰼶",
        "image-night": "snow",
    },
    "350": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "353": {
        "description": "LightShowers",
        "icon": "󰼳",
        "image": "rain",
        "icon-night": "󰼳",
        "image-night": "rain",
    },
    "356": {
        "description": "HeavyShowers",
        "icon": "󰖖",
        "image": "rain",
        "icon-night": "󰖖",
        "image-night": "rain",
    },
    "359": {
        "description": "HeavyRain",
        "icon": "󰖖",
        "image": "rain",
        "icon-night": "󰖖",
        "image-night": "rain",
    },
    "362": {
        "description": "LightSleetShowers",
        "icon": "󰼵",
        "image": "sleet",
        "icon-night": "󰼵",
        "image-night": "sleet",
    },
    "365": {
        "description": "HeavySleetShowers",
        "icon": "󰼵",
        "image": "sleet",
        "icon-night": "󰼵",
        "image-night": "sleet",
    },
    "368": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "371": {
        "description": "HeavySleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
    "374": {
        "description": "HeavySnowShowers",
        "icon": "󰼶",
        "image": "snow",
        "icon-night": "󰼶",
        "image-night": "snow",
    },
    "377": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "sleet",
        "icon-night": "󰙿",
        "image-night": "sleet",
    },
}

volume_text_icons = {
    "overamplified": "󰕾",
    "high": "󰕾",
    "medium": "󰖀",
    "low": "󰕿",
    "muted": "󰝟",
}

volume_text_icons = {
    "overamplified": "󰕾",
    "high": "󰕾",
    "medium": "󰖀",
    "low": "󰕿",
    "muted": "󰝟",
}

brightness_text_icons = {
    "off": "",  # lowest brightness
    "low": "",
    "medium": "",
    "high": "",  # highest brightness
}

icons = {
    "missing": "image-missing-symbolic",
    "nix": {
        "nix": "nix-snowflake-symbolic",
    },
    "app": {
        "terminal": "terminal-symbolic",
    },
    "fallback": {
        "executable": "application-x-executable",
        "notification": "dialog-information-symbolic",
        "video": "video-x-generic-symbolic",
        "audio": "audio-x-generic-symbolic",
    },
    "ui": {
        "close": "window-close-symbolic",
        "colorpicker": "color-select-symbolic",
        "info": "info-symbolic",
        "link": "external-link-symbolic",
        "lock": "system-lock-screen-symbolic",
        "menu": "open-menu-symbolic",
        "refresh": "view-refresh-symbolic",
        "search": "system-search-symbolic",
        "settings": "emblem-system-symbolic",
        "themes": "preferences-desktop-theme-symbolic",
        "tick": "object-select-symbolic",
        "time": "hourglass-symbolic",
        "toolbars": "toolbars-symbolic",
        "warning": "dialog-warning-symbolic",
        "avatar": "avatar-default-symbolic",
        "arrow": {
            "right": "pan-end-symbolic",
            "left": "pan-start-symbolic",
            "down": "pan-down-symbolic",
            "up": "pan-up-symbolic",
        },
    },
    "audio": {
        "mic": {
            "muted": "microphone-disabled-symbolic",
            "low": "microphone-sensitivity-low-symbolic",
            "medium": "microphone-sensitivity-medium-symbolic",
            "high": "microphone-sensitivity-high-symbolic",
        },
        "volume": {
            "muted": "audio-volume-muted-symbolic",
            "low": "audio-volume-low-symbolic",
            "medium": "audio-volume-medium-symbolic",
            "high": "audio-volume-high-symbolic",
            "overamplified": "audio-volume-overamplified-symbolic",
        },
        "type": {
            "headset": "audio-headphones-symbolic",
            "speaker": "audio-speakers-symbolic",
            "card": "audio-card-symbolic",
        },
        "mixer": "mixer-symbolic",
    },
    "powerprofile": {
        "balanced": "power-profile-balanced-symbolic",
        "power-saver": "power-profile-power-saver-symbolic",
        "performance": "power-profile-performance-symbolic",
    },
    "battery": {
        "charging": "battery-flash-symbolic",
        "warning": "battery-empty-symbolic",
    },
    "bluetooth": {
        "enabled": "bluetooth-active-symbolic",
        "disabled": "bluetooth-disabled-symbolic",
    },
    "brightness": {
        "indicator": "display-brightness-symbolic",
        "keyboard": "keyboard-brightness-symbolic",
        "screen": "display-brightness-symbolic",
    },
    "powermenu": {
        "sleep": "weather-clear-night-symbolic",
        "reboot": "system-reboot-symbolic",
        "logout": "system-log-out-symbolic",
        "shutdown": "system-shutdown-symbolic",
    },
    "recorder": {
        "recording": "media-record-symbolic",
        "stopped": "media-record-symbolic",
    },
    "notifications": {
        "noisy": "org.gnome.Settings-notifications-symbolic",
        "silent": "notifications-disabled-symbolic",
        "message": "chat-bubbles-symbolic",
    },
    "trash": {
        "full": "user-trash-full-symbolic",
        "empty": "user-trash-symbolic",
    },
    "mpris": {
        "shuffle": {
            "enabled": "media-playlist-shuffle-symbolic",
            "disabled": "media-playlist-consecutive-symbolic",
        },
        "loop": {
            "none": "media-playlist-repeat-symbolic",
            "track": "media-playlist-repeat-song-symbolic",
            "playlist": "media-playlist-repeat-symbolic",
        },
        "playing": "media-playback-pause-symbolic",
        "paused": "media-playback-start-symbolic",
        "stopped": "media-playback-start-symbolic",
        "prev": "media-skip-backward-symbolic",
        "next": "media-skip-forward-symbolic",
    },
    "system": {
        "cpu": "org.gnome.SystemMonitor-symbolic",
        "ram": "drive-harddisk-solidstate-symbolic",
        "temp": "temperature-symbolic",
    },
    "color": {
        "dark": "dark-mode-symbolic",
        "light": "light-mode-symbolic",
    },
}
