common_text_icons = {
    "playing": "",
    "paused": "",
    "power": "",
    "cpu": "",
    "memory": "",
    "storage": "󰋊",
    "updates": "󱧘",
    "thermometer": "",
}


distro_text_icons = {
    "deepin": "",
    "fedora": "",
    "arch": "",
    "nixos": "",
    "debian": "",
    "opensuse-tumbleweed": "",
    "ubuntu": "",
    "endeavouros": "",
    "manjaro": "",
    "popos": "",
    "garuda": "",
    "zorin": "",
    "mxlinux": "",
    "arcolinux": "",
    "gentoo": "",
    "artix": "",
    "centos": "",
    "hyperbola": "",
    "kubuntu": "",
    "mandriva": "",
    "xerolinux": "",
    "parabola": "",
    "void": "",
    "linuxmint": "",
    "archlabs": "",
    "devuan": "",
    "freebsd": "",
    "openbsd": "",
    "slackware": "",
}

# sourced from wttr.in

weather_text_icons = {
    "113": {"description": "Sunny", "icon": "󰖙"},
    "116": {"description": "PartlyCloudy", "icon": "󰖕"},
    "119": {"description": "Cloudy", "icon": "󰖐"},
    "122": {"description": "VeryCloudy", "icon": "󰖕"},
    "143": {"description": "Fog", "icon": "󰖑"},
    "176": {"description": "LightShowers", "icon": "󰼳"},
    "179": {"description": "LightSleetShowers", "icon": "󰼵"},
    "182": {"description": "LightSleet", "icon": "󰙿"},
    "185": {"description": "LightSleet", "icon": "󰙿"},
    "200": {"description": "ThunderyShowers", "icon": "󰙾"},
    "227": {"description": "LightSnow", "icon": "󰼴"},
    "230": {"description": "HeavySnow", "icon": "󰼶"},
    "248": {"description": "Fog", "icon": "󰖑"},
    "260": {"description": "Fog", "icon": "󰖑"},
    "263": {"description": "LightShowers", "icon": "󰼳"},
    "266": {"description": "LightRain", "icon": "󰼳"},
    "281": {"description": "LightSleet", "icon": "󰙿"},
    "284": {"description": "LightSleet", "icon": "󰙿"},
    "293": {"description": "LightRain", "icon": "󰼳"},
    "296": {"description": "LightRain", "icon": "󰼳"},
    "299": {"description": "HeavyShowers", "icon": "󰖖"},
    "302": {"description": "HeavyRain", "icon": "󰖖"},
    "305": {"description": "HeavyShowers", "icon": "󰖖"},
    "308": {"description": "HeavyRain", "icon": "󰖖"},
    "311": {"description": "LightSleet", "icon": "󰙿"},
    "314": {"description": "LightSleet", "icon": "󰙿"},
    "317": {"description": "LightSleet", "icon": "󰙿"},
    "320": {"description": "LightSnow", "icon": "󰼴"},
    "323": {"description": "LightSnowShowers", "icon": "󰼵"},
    "326": {"description": "LightSnowShowers", "icon": "󰼵"},
    "329": {"description": "HeavySnow", "icon": "󰼶"},
    "332": {"description": "HeavySnow", "icon": "󰼶"},
    "335": {"description": "HeavySnowShowers", "icon": "󰼵"},
    "338": {"description": "HeavySnow", "icon": "󰼶"},
    "350": {"description": "LightSleet", "icon": "󰙿"},
    "353": {"description": "LightShowers", "icon": "󰼳"},
    "356": {"description": "HeavyShowers", "icon": "󰖖"},
    "359": {"description": "HeavyRain", "icon": "󰖖"},
    "362": {"description": "LightSleetShowers", "icon": "󰼵"},
    "365": {"description": "LightSleetShowers", "icon": "󰼵"},
    "368": {"description": "LightSnowShowers", "icon": "󰼵"},
    "371": {"description": "HeavySnowShowers", "icon": "󰼵"},
    "374": {"description": "LightSleetShowers", "icon": "󰼵"},
    "377": {"description": "LightSleet", "icon": "󰙿"},
    "386": {"description": "ThunderyShowers", "icon": "󰙾"},
    "389": {"description": "ThunderyHeavyRain", "icon": "󰙾"},
    "392": {"description": "ThunderySnowShowers", "icon": "󰼶"},
    "395": {"description": "HeavySnowShowers", "icon": "󰼵"},
}


weather_text_icons_v2 = {
    "113": {
        "description": "Sunny",
        "icon": "󰖙",
        "image": "clear-day",
        "lottie": "clear-day",
    },
    "116": {
        "description": "PartlyCloudy",
        "icon": "󰖕",
        "image": "cloudy",
        "lottie": "cloudy",
    },
    "119": {
        "description": "Cloudy",
        "icon": "󰖐",
        "image": "cloudy",
        "lottie": "cloudy",
    },
    "122": {
        "description": "VeryCloudy",
        "icon": "󰖕",
        "image": "cloudy",
        "lottie": "cloudy",
    },
    "143": {"description": "Fog", "icon": "󰖑", "image": "fog", "lottie": "fog"},
    "176": {
        "description": "LightShowers",
        "icon": "󰼳",
        "image": "weather-showers-scattered-symbolic",
        "lottie": "weather-showers-scattered-symbolic",
    },
    "179": {
        "description": "LightSleetShowers",
        "icon": "󰼵",
        "image": "weather-sleet-showers-symbolic",
        "lottie": "weather-sleet-showers-symbolic",
    },
    "182": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "185": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "200": {
        "description": "ThunderyShowers",
        "icon": "󰙾",
        "image": "weather-thunderstorms-symbolic",
        "lottie": "weather-thunderstorms-symbolic",
    },
    "227": {
        "description": "LightSnow",
        "icon": "󰼴",
        "image": "weather-snow-symbolic",
        "lottie": "weather-snow-symbolic",
    },
    "230": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "weather-snow-heavy-symbolic",
        "lottie": "weather-snow-heavy-symbolic",
    },
    "248": {
        "description": "Fog",
        "icon": "󰖑",
        "image": "weather-fog-symbolic",
        "lottie": "weather-fog-symbolic",
    },
    "260": {
        "description": "Fog",
        "icon": "󰖑",
        "image": "weather-fog-symbolic",
        "lottie": "weather-fog-symbolic",
    },
    "263": {
        "description": "LightShowers",
        "icon": "󰼳",
        "image": "weather-showers-symbolic",
        "lottie": "weather-showers-symbolic",
    },
    "266": {
        "description": "LightRain",
        "icon": "󰼳",
        "image": "weather-rain-symbolic",
        "lottie": "weather-rain-symbolic",
    },
    "281": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "284": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "293": {
        "description": "LightRain",
        "icon": "󰼳",
        "image": "weather-rain-symbolic",
        "lottie": "weather-rain-symbolic",
    },
    "296": {
        "description": "LightRain",
        "icon": "󰼳",
        "image": "weather-rain-symbolic",
        "lottie": "weather-rain-symbolic",
    },
    "299": {
        "description": "HeavyShowers",
        "icon": "󰖖",
        "image": "weather-rain-heavy-symbolic",
        "lottie": "weather-rain-heavy-symbolic",
    },
    "302": {
        "description": "HeavyRain",
        "icon": "󰖖",
        "image": "weather-rain-heavy-symbolic",
        "lottie": "weather-rain-heavy-symbolic",
    },
    "305": {
        "description": "HeavyShowers",
        "icon": "󰖖",
        "image": "weather-rain-heavy-symbolic",
        "lottie": "weather-rain-heavy-symbolic",
    },
    "308": {
        "description": "HeavyRain",
        "icon": "󰖖",
        "image": "weather-rain-heavy-symbolic",
        "lottie": "weather-rain-heavy-symbolic",
    },
    "311": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "314": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "317": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "320": {
        "description": "LightSnow",
        "icon": "󰼴",
        "image": "weather-snow-symbolic",
        "lottie": "weather-snow-symbolic",
    },
    "323": {
        "description": "LightSnowShowers",
        "icon": "󰼵",
        "image": "weather-snow-showers-symbolic",
        "lottie": "weather-snow-showers-symbolic",
    },
    "326": {
        "description": "LightSnowShowers",
        "icon": "󰼵",
        "image": "weather-snow-showers-symbolic",
        "lottie": "weather-snow-showers-symbolic",
    },
    "329": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "weather-snow-heavy-symbolic",
        "lottie": "weather-snow-heavy-symbolic",
    },
    "332": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "weather-snow-heavy-symbolic",
        "lottie": "weather-snow-heavy-symbolic",
    },
    "335": {
        "description": "HeavySnowShowers",
        "icon": "󰼵",
        "image": "weather-snow-heavy-symbolic",
        "lottie": "weather-snow-heavy-symbolic",
    },
    "338": {
        "description": "HeavySnow",
        "icon": "󰼶",
        "image": "extreme-snow",
        "lottie": "extreme-snow",
    },
    "350": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "353": {
        "description": "LightShowers",
        "icon": "󰼳",
        "image": "weather-showers-scattered-symbolic",
        "lottie": "weather-showers-scattered-symbolic",
    },
    "356": {
        "description": "HeavyShowers",
        "icon": "󰖖",
        "image": "weather-rain-heavy-symbolic",
        "lottie": "weather-rain-heavy-symbolic",
    },
    "359": {
        "description": "HeavyRain",
        "icon": "󰖖",
        "image": "weather-rain-heavy-symbolic",
        "lottie": "weather-rain-heavy-symbolic",
    },
    "362": {
        "description": "LightSleetShowers",
        "icon": "󰼵",
        "image": "weather-sleet-showers-symbolic",
        "lottie": "weather-sleet-showers-symbolic",
    },
    "365": {
        "description": "LightSleetShowers",
        "icon": "󰼵",
        "image": "weather-sleet-showers-symbolic",
        "lottie": "weather-sleet-showers-symbolic",
    },
    "368": {
        "description": "LightSnowShowers",
        "icon": "󰼵",
        "image": "weather-snow-showers-symbolic",
        "lottie": "weather-snow-showers-symbolic",
    },
    "371": {
        "description": "HeavySnowShowers",
        "icon": "󰼵",
        "image": "weather-snow-heavy-symbolic",
        "lottie": "weather-snow-heavy-symbolic",
    },
    "374": {
        "description": "LightSleetShowers",
        "icon": "󰼵",
        "image": "weather-sleet-showers-symbolic",
        "lottie": "weather-sleet-showers-symbolic",
    },
    "377": {
        "description": "LightSleet",
        "icon": "󰙿",
        "image": "weather-sleet-symbolic",
        "lottie": "weather-sleet-symbolic",
    },
    "386": {
        "description": "ThunderyShowers",
        "icon": "󰙾",
        "image": "weather-thunderstorms-symbolic",
        "lottie": "weather-thunderstorms-symbolic",
    },
    "389": {
        "description": "ThunderyHeavyRain",
        "icon": "󰙾",
        "image": "weather-thunderstorms-symbolic",
        "lottie": "weather-thunderstorms-symbolic",
    },
    "392": {
        "description": "ThunderySnowShowers",
        "icon": "󰼶",
        "image": "thunderstorms-day-snow",
        "lottie": "thunderstorms-day-snow",
    },
    "395": {
        "description": "HeavySnowShowers",
        "icon": "󰼵",
        "image": "weather-snow-heavy-symbolic",
        "lottie": "weather-snow-heavy-symbolic",
    },
}


volume_text_icons = {
    "overamplified": "󰕾",
    "high": "󰕾",
    "medium": "󰖀",
    "low": "󰕿",
    "muted": "󰝟",
}


volume_text_icons = {
    "overamplified": "󰕾",
    "high": "󰕾",
    "medium": "󰖀",
    "low": "󰕿",
    "muted": "󰝟",
}

brightness_text_icons = {
    "off": "",  # lowest brightness
    "low": "",
    "medium": "",
    "high": "",  # highest brightness
}


icons = {
    "missing": "image-missing-symbolic",
    "nix": {
        "nix": "nix-snowflake-symbolic",
    },
    "app": {
        "terminal": "terminal-symbolic",
    },
    "fallback": {
        "executable": "application-x-executable",
        "notification": "dialog-information-symbolic",
        "video": "video-x-generic-symbolic",
        "audio": "audio-x-generic-symbolic",
    },
    "ui": {
        "close": "window-close-symbolic",
        "colorpicker": "color-select-symbolic",
        "info": "info-symbolic",
        "link": "external-link-symbolic",
        "lock": "system-lock-screen-symbolic",
        "menu": "open-menu-symbolic",
        "refresh": "view-refresh-symbolic",
        "search": "system-search-symbolic",
        "settings": "emblem-system-symbolic",
        "themes": "preferences-desktop-theme-symbolic",
        "tick": "object-select-symbolic",
        "time": "hourglass-symbolic",
        "toolbars": "toolbars-symbolic",
        "warning": "dialog-warning-symbolic",
        "avatar": "avatar-default-symbolic",
        "arrow": {
            "right": "pan-end-symbolic",
            "left": "pan-start-symbolic",
            "down": "pan-down-symbolic",
            "up": "pan-up-symbolic",
        },
    },
    "audio": {
        "mic": {
            "muted": "microphone-disabled-symbolic",
            "low": "microphone-sensitivity-low-symbolic",
            "medium": "microphone-sensitivity-medium-symbolic",
            "high": "microphone-sensitivity-high-symbolic",
        },
        "volume": {
            "muted": "audio-volume-muted-symbolic",
            "low": "audio-volume-low-symbolic",
            "medium": "audio-volume-medium-symbolic",
            "high": "audio-volume-high-symbolic",
            "overamplified": "audio-volume-overamplified-symbolic",
        },
        "type": {
            "headset": "audio-headphones-symbolic",
            "speaker": "audio-speakers-symbolic",
            "card": "audio-card-symbolic",
        },
        "mixer": "mixer-symbolic",
    },
    "powerprofile": {
        "balanced": "power-profile-balanced-symbolic",
        "power-saver": "power-profile-power-saver-symbolic",
        "performance": "power-profile-performance-symbolic",
    },
    "battery": {
        "charging": "battery-flash-symbolic",
        "warning": "battery-empty-symbolic",
    },
    "bluetooth": {
        "enabled": "bluetooth-active-symbolic",
        "disabled": "bluetooth-disabled-symbolic",
    },
    "brightness": {
        "indicator": "display-brightness-symbolic",
        "keyboard": "keyboard-brightness-symbolic",
        "screen": "display-brightness-symbolic",
    },
    "powermenu": {
        "sleep": "weather-clear-night-symbolic",
        "reboot": "system-reboot-symbolic",
        "logout": "system-log-out-symbolic",
        "shutdown": "system-shutdown-symbolic",
    },
    "recorder": {
        "recording": "media-record-symbolic",
    },
    "notifications": {
        "noisy": "org.gnome.Settings-notifications-symbolic",
        "silent": "notifications-disabled-symbolic",
        "message": "chat-bubbles-symbolic",
    },
    "trash": {
        "full": "user-trash-full-symbolic",
        "empty": "user-trash-symbolic",
    },
    "mpris": {
        "shuffle": {
            "enabled": "media-playlist-shuffle-symbolic",
            "disabled": "media-playlist-consecutive-symbolic",
        },
        "loop": {
            "none": "media-playlist-repeat-symbolic",
            "track": "media-playlist-repeat-song-symbolic",
            "playlist": "media-playlist-repeat-symbolic",
        },
        "playing": "media-playback-pause-symbolic",
        "paused": "media-playback-start-symbolic",
        "stopped": "media-playback-start-symbolic",
        "prev": "media-skip-backward-symbolic",
        "next": "media-skip-forward-symbolic",
    },
    "system": {
        "cpu": "org.gnome.SystemMonitor-symbolic",
        "ram": "drive-harddisk-solidstate-symbolic",
        "temp": "temperature-symbolic",
    },
    "color": {
        "dark": "dark-mode-symbolic",
        "light": "light-mode-symbolic",
    },
}
